name: Build pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: StardewDumper.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - uses: nuget/setup-nuget@v1
    - run: nuget restore $env:Solution_Name

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      run: msbuild "StardewDumper/StardewDumper.csproj" /p:Configuration=$env:Configuration
      env:
        Configuration: Release
        
    - name: Upload zip
      uses: actions/upload-artifact@v2.2.4
      with:
        path: "bin/release/StarDewDumper 1.0.0.zip"
